### ISSUE TITLE
EnsureSuccessStatusCode is not enough when you need the response content

### ISSUE THREAD

**Issue by fabmoll** [igorkulman/Kulman.WPA81.BaseRestService#11]
I'm using an API returning a 400 StatusCode (Bad Request) but I need the response content because the API store the error message there.

With the default EnsureSuccessStatusCode I don't have the information.

https://github.com/igorkulman/Kulman.WPA81.BaseRestService/blob/master/Kulman.WPA81.BaseRestService/Services/Abstract/BaseRestService.cs#L421

I've a fix and I'll create a pull request

**Comment by igorkulman** [comment]
One more thing unrelated to the pull request. You can always use the methods returning `Task<HttpResponseMessage>` if you need full control over the response, but you have to do the deserialization by yourself.

**Comment by fabmoll** [comment]
Well my solution isn't better. It's better to use your connectionexception instead of a new one.

For your last comment you're right I can use the GetRawResponse method and then deserialize the response.

If I use that we do not change your code :)

If I add the field in your exception it's more for my personal use.

In fact I don't mind to deserialize in my project.

It depends of your choice :)


Just a question, you never need the response when you EnsureSuccessStatusCode throw an exception in your project?

Envoyé à partir de mon Windows Phone
________________________________
De : Igor Kulman<mailto:notifications@github.com>
Envoyé : ‎03-‎01-‎16 14:10
À : igorkulman/Kulman.WPA81.BaseRestService<mailto:Kulman.WPA81.BaseRestService@noreply.github.com>
Cc : Fabrice Moll<mailto:fabrice.moll@hotmail.com>
Objet : Re: [Kulman.WPA81.BaseRestService] EnsureSuccessStatusCode is not enough when you need the response content (#11)

One more thing unrelated to the pull request. You can always use the methods returning `Task<HttpResponseMessage>` if you need full control over the response, but you have to do the deserialization by yourself.

---

**Comment by igorkulman** [comment]
Not in the two projects I currently use. Maybe I will need it in a third project, you never know.

If you make the change I suggested, I will accept it. Maybe someone else will find it useful also (I hope it is not just the two of use using this library :).

**Comment by igorkulman** [comment]
Fixed in #12 and pushed to Nuget as 1.3.0.
