### ISSUE TITLE
Add Task<T> Delete<T>

### ISSUE THREAD

**Issue by fabmoll** [igorkulman/Kulman.WPA81.BaseRestService#7]
As I can see there is only on method delete 
```
protected Task Delete([NotNull] string url)
```

I'm using an API returning a json response from a Delete and it could be nice to have a delete signature like this :
```
protected Task<T> Delete<T>([NotNull] string url)
```

**Comment by fabmoll** [comment]
Damn you're fast :+1: 
Thank you !!

**Comment by igorkulman** [comment]
Good timing :) I also pushed a new Nuget package.
